server:
  port: 8100

spring:
  application:
    name: makeup-service

  datasource:
    url: jdbc:mysql://localhost:3306/akmakeovers
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  secret: "0123456789abcdef"
  expiration: 86400000  # 1 day in milliseconds


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE



